# Generated by Django 5.0 on 2023-12-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField()),
                ("text", models.CharField(max_length=2000)),
                ("img", models.ImageField(upload_to="img")),
                ("text_img", models.CharField(max_length=2000)),
                ("spreadsheet", models.FileField(upload_to="xlsx")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
